### ISSUE TITLE
Bug: Only shows *_info metrics for metrics with data

### ISSUE THREAD

**Issue by daviddetorres** [ivx/yet-another-cloudwatch-exporter#171]
Before, all info metrics were shown, and now only the ones with data (as reported in #151). Both are compatible with different scenarios. 

Here there are 2 options: 

1. All *_info metrics are always shown
2. New config parameter to only show info for metrics with data

Can anyone share use cases and thoughts on this?

**Comment by nhinds** [comment]
In #151 I mentioned that I'm currently (with version 0.14.x) using the `*_info` metrics to detect when there are loadbalancers without healthy host metrics for ECS/fargate target groups, something like `aws_alb_info{...} unless on (name) aws_alb_tg_healthy_host_count_average > 0`. I'm using that slightly weird query because the HealthyHost and UnHealthyHost metrics completely disappear from CloudWatch when there are no targets in the target group, which can happen with ECS.

I might be able to get the same outcome for 0 healthy hosts by setting `nilToZero` on the `aws_alb_tg_healthy_host_count_average` metric once #170 is fixed, and just using `aws_alb_tg_healthy_host_count_average == 0`, so that's not super critical.

I'm also using the `*_info` metrics to populate dropdowns in Grafana dashboards.

I believe that Prometheus marks metrics that are no longer returned from exporters as "stale", and it won't return the series at all for an instant selector if the series was stale during its last scrape. So if this cloudwatch exporter returns `*_info` metrics for one scrape and not the next, I think they will end up not being shown in my Grafana dropdowns even if there were some metrics at some point during the selected time period.

**Comment by thomaspeitz** [comment]
@daviddetorres @nhinds  - Actually it is a bug that they are not shown. So lets add info metrics always and make this not configurable.

**Comment by daviddetorres** [comment]
Hmmm... in some contexts that you are charged for time series and you need to reduce them, the info of some resources that you do not want to monitor can be skipped.

An example would be S3 buckets with hourly metrics. You can have 300 info metrics but only 10 useful (the ones you set up the hourly metrics). This is a real use case that we had, but more can rise.

If not configured, it will show all, but giving the option to limit them to only the resources with metrics can be useful in some escenarios that require metrics pruning.

What are your thoughts?

**Comment by thomaspeitz** [comment]
@daviddetorres - For example nginx collects a lot metrics as well or cadvisor. We just skip collecting them on prometheus by selecting only some metrics during scraping. So the collector can be stupid and prometheus takes this task for us.

Example:
![image](https://user-images.githubusercontent.com/8327755/86919295-4cd37300-c128-11ea-9696-ca6c3b62323a.png)

**Comment by daviddetorres** [comment]
Accepted. :+1: 
I'll modify the PR to make it always get all the info tags.
