### ISSUE TITLE
Issues With Getting SQS Metrics

### ISSUE THREAD

**Issue by singhjagmohan1000** [ivx/yet-another-cloudwatch-exporter#239]
I am using Yace to export metrics form Cloudwatch. Yace is not getting metrics for SQS queues which are not tagged. I am able to get the metrics for SQS queues which are tagged.

**Comment by agung-kargo** [comment]
Also facing the same issue. Is there any workaround or any pointer where we can fix this thing?

**Comment by agung-kargo** [comment]
Okay, i think this is by design, since auto discover job utilizes tag anyway in the first place. CMIIW.

So in my case, I have to tag all sqs instances in my aws account. Have created a simple script for that here: https://gist.github.com/bangau1/ccb73b826c22ab719e35218f0abd8075

**Comment by singhjagmohan1000** [comment]
We are also working on terraform to update all sqs queues, for now using custom exporter to fetch sqs metrics

**Comment by daviddetorres** [comment]
Hi, 

[Here](https://github.com/ivx/yet-another-cloudwatch-exporter/issues/185#issuecomment-655461918) is the explanation of why adding tags to the resources is a hard-requisite in order to be monitored with this exporter. 

Personally, I use to add a tag monitor=True to all the resources that I want to monitor to ensure that at least they have that tag.

**Comment by thomaspeitz** [comment]
Yeah there won't be any support for resources which are not tagged. This is a base concept of this exporter. Thanks for sharing tipps here and the script for tagging resouces :)

I am cloing this here as it is not a bug. It is intended that untagged resources are not found.
