### ISSUE TITLE
Add rds provisioned storage size as own metric

### ISSUE THREAD

**Issue by arnitolog** [ivx/yet-another-cloudwatch-exporter#48]
Hello,

Is there any way to get some metrics directly from RDS? For example the size of provisioned storage. So, If we will know it we will be able to calculate the percent of RDS storage usage.

**Comment by izo3** [comment]
You can use something like this (might need some tweaks):

`
#!/bin/bash

# Find out AWS RDS total/free space
#
# This file will generate output with total space and free space per RDS instance in:
#
#     /etc/node_exporter/rds_total_space.prom
#     /etc/node_exporter/rds_free_space.prom

# Get our region
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document |jq -r .region)
starttime="$(date -u -d '5 minutes ago' '+%Y-%m-%dT%T')"
end="$(date -u '+%Y-%m-%dT%T')"

# Get RDS Arn, DBInstanceIdentifier and AllocatedStorage
rds_instances=$(aws rds describe-db-instances --region $region |jq ".DBInstances[] | {ARN: .DBInstanceArn, DBInstanceIdentifier: .DBInstanceIdentifier, AllocatedStorage: .AllocatedStorage}")

# Iterate over the intance names in order to get the total free space
rds_details() {
  # Truncate the output files
  echo > /etc/node_exporter/rds_total_space.prom
  echo > /etc/node_exporter/rds_free_space.prom
  # Get instance names only
  db_instances_name=$(echo $rds_instances |jq -r .DBInstanceIdentifier)

  for db_instance in $db_instances_name; do
    if [[ "$db_instance" ]]; then

     free_space=$(aws --region $region cloudwatch get-metric-statistics \
          --namespace AWS/RDS --metric-name FreeStorageSpace \
          --start-time $starttime --end-time $end --period 300 \
          --statistics Average \
          --dimensions "Name=DBInstanceIdentifier, Value=${db_instance}" \
          | jq -r ".Datapoints[].Average")
     free_space_in_gigabytes=$(bc <<< "scale=2; $free_space/1024/1024/1024")

     rds_storage=$(echo $rds_instances | jq -r ". | select(.DBInstanceIdentifier==\"$db_instance\")| .AllocatedStorage")
     rds_arn=$(echo $rds_instances | jq -r ". | select(.DBInstanceIdentifier==\"$db_instance\")| .ARN")
     rds_environment=$(aws rds list-tags-for-resource --resource-name ${rds_arn} | jq -r ".TagList[] | select(.Key==\"environment\") | .Value")

     # Update a file that will be parsed by node_exporter
     echo "rds_total_space{service=\"rds\",environment=\"$rds_environment\",instance=\"$db_instance\"} ${rds_storage}" >> /etc/node_exporter/rds_total_space.prom
     echo "rds_free_space{service=\"rds\",environment=\"$rds_environment\",instance=\"$db_instance\"} ${free_space_in_gigabytes}" >> /etc/node_exporter/rds_free_space.prom
    fi
  done
}

rds_details
`

**Comment by tsupertramp** [comment]
@arnitolog - In short "No, this is currently not possible."

Long Story:
Actually in the initial implementation of the scraper i implemented those metrics for some serves and added those to the info metrics.

Currently i am unsure if this is really needed and would like to avoid this added complexity.

Next questions are only interesting if you need the provisioned storage size for alerting and not visualization:

Do you have so many different sized databases? - Else i would suggest that you tag them e.g. with "Storage-Size" - "100G" - Then you can define different alerts for each tag.

Or how we solve it at our company is that we use forecasted alerts. We are not interested about the percentage, we are interested if it will be full in x days. Then we alert.

This is one rule as example. It checks the change in the last 24h and alerts based on that if it will be full in 32 days. This allows to detect changes in data usage a lot faster and we have more time to react. Less stress during nights :)

```(predict_linear(aws_rds_free_storage_space_minimum[1d], 86400 * 32) + on (name) group_left(tag_type) aws_rds_info) / 1024 / 1024 / 1024 < 0```

I hope it helps without code changes.

**Comment by arnitolog** [comment]
Thanks a lot, Thomas. 
Yes, unfortunately, we have several completely different storage types (8,20,60,200,500,700Gb)
Also thought about a tag with the storage size. And you suggested an interesting approach with predict_linear. I will take a close look at it. 
Thanks for the advice and, of course, for the excellent tool

**Comment by tsupertramp** [comment]
I will close this here. Please tag me here if you want to get it reopened.
