### ISSUE TITLE
Please explain length, period, and delay

### ISSUE THREAD

**Issue by AceHack** [ivx/yet-another-cloudwatch-exporter#97]
I don't understand these values

**Comment by thomaspeitz** [comment]
Hey @AceHack,

```When you retrieve statistics, you can specify a period, start time, and end time. These parameters determine the overall length of time associated with the statistics. The default values for the start time and end time get you the last hour's worth of statistics. The values that you specify for the start time and end time determine how many periods CloudWatch returns. For example, retrieving statistics using the default values for the period, start time, and end time returns an aggregated set of statistics for each minute of the previous hour. If you prefer statistics aggregated in ten-minute blocks, specify a period of 600. For statistics aggregated over the entire hour, specify a period of 3600.``` - https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html

So yace uses not a start and end time. It uses a length to calculate it automatically. If you scrape yace the end time is the current time (minus an optional delay). Start Time is calculated through length. So if it is for example 13:00 a clock and you set length to 5 minutes. The data from 12:55 to 13:00 will be scraped. If you set period to 60 seconds. You get 5 values. If you set it to 5 minutes you get one value. If you for example use max. You get 5 max value data points. Then yace takes the average of those. Delay would allow you to scrape at 13:00 but get values from 12:50 to 12:55.

"Only custom metrics that you define with a storage resolution of 1 second support sub-minute periods. Even though the option to set a period below 60 is always available in the console, you should select a period that aligns to how the metric is stored. " - https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html

**Comment by dudicoco** [comment]
@thomaspeitz can you please help me get a better understanding of length and period?

I'm using the following configuration:
```
  - type: alb
    metrics:
    - name: UnHealthyHostCount
      statistics: [Maximum]
      period: 60
      length: 600
```

Within prometheus I see the metrics with a delay of ~3 minutes, I would like to minimize this delay as much as possible because I would like to alert on the metrics with alertmanager.

1. Since ALB cloudwatch metrics have a 1 minute granularity, would it be ideal to use a period of 60 to match these data points?
2. If Prometheus is scraping every 1 minute, is there a point in setting the length to anything longer than 60-120? What are the pros and cons of setting low/high length period?

Thanks!

**Comment by thomaspeitz** [comment]
Hey i come back to you in a week (vacation) - Greetings, Thomas

dudicoco <notifications@github.com> schrieb am So. 28. Juni 2020 um 19:45:

**Comment by thomaspeitz** [comment]
1. - Yes, this is true.
2. - Sometimes it makes sense to look at the average of the last minutes, so if you have spikes you are not alerted. So it can make sense to use average, period of 60 and length of 600 for example. It would show every minute the average of the last 5 minutes. I hope this explains it.

Please close it if your question has been solved @dudicoco

**Comment by dudicoco** [comment]
Hi @thomaspeitz, thank you for the reply.

I'm not sure I understand the explanation regarding the length, why would a period of 60 and length of 600 should the average of the last 5 minutes? 600 is 10 minutes, and why wouldn't it show every minute the average of that minute?

**Comment by thomaspeitz** [comment]
600 => is 10 minutes right. My mistake.

If you want the average of the last minute, please set period to 60 and length to 60 as well. 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html

**Comment by dudicoco** [comment]
@thomaspeitz I assume the "Aggregation" section is the most relevant in that link?

I'm still a bit confused about the average of each data point. If I set a period of 60 and a length of 3600, each data point would be an average of the last hour? Wouldn't it make more sense to get data points with a period of 60 and a length of 60 and then use the average function within the prometheus query?

Are there any downsides in using a short length of 60 seconds?

Thanks again for your help! :)

**Comment by thomaspeitz** [comment]
Yes, we use it that way: `Wouldn't it make more sense to get data points with a period of 60 and a length of 60 and then use the average function within the prometheus query?`

Cloudwatch works differently and as we use the API we just translate those values of the api into the exporter. I would suggest that you use either 1m intervals or 5m intervals and use average of prometheus. (5 api calls in 5 minutes).

If you want to use less api calls, you can use average of 1 minute in 5 minute intervals to ensure that you find spikes but have less api calls. (in this case 1 every 5 minute)

**Comment by dudicoco** [comment]
Hi @thomaspeitz,

I've tried using a length of 60, but then I noticed that the data points imported by YACE are different than the CloudWatch metrics within the AWS console.

After a lot of digging i've found out that due to the fact that the YACE `StartTime` and `EndTime` seconds are not zeroed, two data points are received for the scraping period. For example:
```
# request

  "StartTime": "2020-07-12T11:24:40.039255Z",
  "EndTime": "2020-07-12T11:26:40.039253243Z"
```
# response

  <GetMetricDataResult>
    <MetricDataResults>
      <member>
        <Timestamps>
          <member>2020-07-12T11:25:00Z</member>
          <member>2020-07-12T11:24:00Z</member>
        </Timestamps>
        <Values>
          <member>107.0</member>
          <member>359.0</member>
        </Values>
        <Label>HTTPCode_ELB_4XX_Count</Label>
        <StatusCode>Complete</StatusCode>
      </member>
```

Is there a way to make the seconds within the start and end times equal zero? This should make the imported metrics identical to the CloudWatch metrics.
If it's not possible, perhaps an enhancement is needed for a flag to turn this feature on?

Thanks!

**Comment by dudicoco** [comment]
@thomaspeitz i've noticed that the metrics do not match even if when only one data point is fetched, i've compared the results to the same request using aws cli:

```
# request json aws-cli

{
  "MetricDataQueries": [
      {
          "Id": "test",
          "MetricStat": {
              "Metric": {
                  "Namespace": "AWS/ApplicationELB",
                  "MetricName": "HTTPCode_ELB_4XX_Count",
                  "Dimensions": [
                    {
                      "Name": "LoadBalancer",
                      "Value": "app/mylb"
                    }
                  ]
              },
              "Period": 60,
              "Stat": "Sum",
              "Unit": "Count"
          }
      }
  ],
  "StartTime": "2020-07-12T12:22:11Z",
  "EndTime": "2020-07-12T12:24:11Z"
}
```

```
# response via aws cli

$ aws cloudwatch get-metric-data --cli-input-json file://./metric-data-queries.json --region us-east-1
{
    "Messages": [],
    "MetricDataResults": [
        {
            "Timestamps": [
                "2020-07-12T12:23:00Z",
                "2020-07-12T12:22:00Z"
            ],
            "StatusCode": "Complete",
            "Values": [
                105.0,
                104.0
            ],
            "Id": "test",
            "Label": "HTTPCode_ELB_4XX_Count"
        }
    ]
}
```

```
# request from YACE debug log

Action=GetMetricData&EndTime=2020-07-12T12%3A24%3A11Z&MetricDataQueries.member.1.Id=id_xxx&MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.1.Name=LoadBalancer&MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.1.Value=app%2Fmylb&MetricDataQueries.member.1.MetricStat.Metric.MetricName=HTTPCode_ELB_4XX_Count&MetricDataQueries.member.1.MetricStat.Metric.Namespace=AWS%2FApplicationELB&MetricDataQueries.member.1.MetricStat.Period=60&MetricDataQueries.member.1.MetricStat.Stat=Sum&MetricDataQueries.member.1.ReturnData=true&ScanBy=TimestampDescending&StartTime=2020-07-12T12%3A22%3A11Z&Version=2010-08-01

```

```
# response from YACE debug log

  <GetMetricDataResult>
    <MetricDataResults>
      <member>
        <Timestamps>
          <member>2020-07-12T12:22:00Z</member>
        </Timestamps>
        <Values>
          <member>50.0</member>
        </Values>
        <Label>HTTPCode_ELB_4XX_Count</Label>
        <Id>id_xxx</Id>
        <StatusCode>Complete</StatusCode>
      </member>

```

**Comment by dudicoco** [comment]
@thomaspeitz I've managed to solve all issues and found out the following:

1. There seems to be a bug when using `delay` in the metrics configuration - the value is ignored. Adding delay in top of the service discovery job hierarchy solved this.
2. A delay of 2 minutes is needed with ALB metrics in order to allow enough time for the metrics values to converge.
3. The CloudWatch API rounds down the seconds for start time and end time in the request, this can introduce one extra minute of delay if the scraping always takes place closer to the end of the minute - `19:15:57` will be rounded down to `19:15:00`. I suggest either rounding up or down the current time before each request (`19:15:28` will be rounded down, `19:15:32` will be rounded up).
4. I'm still not sure how YACE is using the data points from the response - when using a period of 60 with a length of 600 will generate 10 data points, but YACE only exposes the last data points in `/metrics` so what difference does it make if we use length of 300 or 3600?

Thank you

**Comment by thomaspeitz** [comment]
1: @dudicoco - Did you use the docs for your version or are you reading docs from master?

2: Yeah, this is something we are not fixing. Not quite sure if we should.

3. Rounding is something we should do! Beginning down, Ending up. I would suggest.

4. If you use average, it would use the average of the 10 data points. https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/aws_cloudwatch.go#L731

Greetings :)

**Comment by dudicoco** [comment]
@thomaspeitz 

1. I've used the docs from master.
2. This is not related to YACE but to the CloudWatch API so there's nothing to fix really, would be helpful to mention it in the readme though.
3. What do you mean by beginning down, ending up?
4. I was testing with sum, I guess that's why I didn't encounter this behaviour. I'm wondering why did you choose to implement this? Could be confusing for the end user as it's not documented. I suggest making this optional with a flag as well. :)

Thanks

**Comment by thomaspeitz** [comment]
1. Please use the release branch for docs of your release. - Would you add this as separate issue please? - That you as user thought master is always last release and we should show somehow that it is not.
2. I do not want to explain cloudwatch here and I won't 😄  This will introduce a lot more questions. I do not want to do support on cloudwatch.
3. Starting point should be rounded down. Ending point should be rounded up. - Would you add this as separate issue please?
4. Fair deal. I think this makes totally sense and should be not the way it is currently. - Would you add this as separate issue please?

Closing this here :) - And we work on your other questions in separate issues.

**Comment by dudicoco** [comment]
@thomaspeitz 

1. I'm not sure how the docs are related? This is a bug. And there are no branches for releases in this project, only master: https://github.com/ivx/yet-another-cloudwatch-exporter/branches
2. The official prometheus cloudwatch exporter mentions this: https://github.com/prometheus/cloudwatch_exporter#timestamps and I think this is valuable information for the end user. The YACE readme FAQ mentions other CloudWatch related issues so why not this one?
3. Will do
4. Will do

**Comment by thomaspeitz** [comment]
1. Sorry meant tags
![image](https://user-images.githubusercontent.com/8327755/87538629-cd502180-c69c-11ea-9b11-04c955580ee1.png)

2. Feel free to PR :)
3. Awesome <3
4. Awesome <3
